// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoJYmw2VYruIFeTTy--NSl2vI-WbLTQI',
    appId: '1:96095979835:web:012c926dbc6c7c6ed08f1e',
    messagingSenderId: '96095979835',
    projectId: 'malaria-e004f',
    authDomain: 'malaria-e004f.firebaseapp.com',
    storageBucket: 'malaria-e004f.appspot.com',
    measurementId: 'G-NTDXJPQ4M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13ZaGnVW6bbASXpKNB_ZLu7TYWhL7OTk',
    appId: '1:96095979835:android:b78d92939ec54943d08f1e',
    messagingSenderId: '96095979835',
    projectId: 'malaria-e004f',
    storageBucket: 'malaria-e004f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA12rSDff3qV3jJHeJSb7gCTddWAUNI8b0',
    appId: '1:96095979835:ios:b2fdc6dab48bf0cdd08f1e',
    messagingSenderId: '96095979835',
    projectId: 'malaria-e004f',
    storageBucket: 'malaria-e004f.appspot.com',
    iosClientId:
        '96095979835-lk3mqlsqv5dma261rva9e3kbpal2j91p.apps.googleusercontent.com',
    iosBundleId: 'com.example.malaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA12rSDff3qV3jJHeJSb7gCTddWAUNI8b0',
    appId: '1:96095979835:ios:b2fdc6dab48bf0cdd08f1e',
    messagingSenderId: '96095979835',
    projectId: 'malaria-e004f',
    storageBucket: 'malaria-e004f.appspot.com',
    iosClientId:
        '96095979835-lk3mqlsqv5dma261rva9e3kbpal2j91p.apps.googleusercontent.com',
    iosBundleId: 'com.example.malaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUoJYmw2VYruIFeTTy--NSl2vI-WbLTQI',
    appId: '1:96095979835:web:8ec93e5074cb69a9d08f1e',
    messagingSenderId: '96095979835',
    projectId: 'malaria-e004f',
    authDomain: 'malaria-e004f.firebaseapp.com',
    storageBucket: 'malaria-e004f.appspot.com',
    measurementId: 'G-NDLKMSQP09',
  );
}
